# Generated by Django 4.2.6 on 2023-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_job_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
